In [8]:
from jutils import *
import numpy as np

In [3]:
counts_by_image = load_cifar10h_labels()

for orig_counts in counts_by_image:

    
    for n_samples in range(2, 24):
    
        counts = orig_counts.copy()
        orig_probs = counts / counts.sum()

        probs = orig_probs.copy()

        samples = []
        while counts.sum() > 0.1:
            pick = np.random.multinomial(1, probs)
            counts -= pick.copy()
            probs = counts / counts.sum()

            samples.append(pick.copy())
            if len(samples) == 25:
                break
        new_probs = np.mean(samples, axis=0)
        print(np.corrcoef(orig_probs, new_probs))
        break

[[1.         0.99921218]
 [0.99921218 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99080533]
 [0.99080533 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99741823]
 [0.99741823 1.        ]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.97798646]
 [0.97798646 1.        ]]
[[1.         0.99972451]
 [0.99972451 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99978474]
 [0.99978474 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99653734]
 [0.99653734 1.        ]]
[[1.         0.99936671]
 [0.99936671 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951381]
 [0.999

[[1.         0.99981664]
 [0.99981664 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99981664]
 [0.99981664 1.        ]]
[[1.         0.99977582]
 [0.99977582 1.        ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99960706]
 [0.99960706 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951325]
 [0.99951325 1.        ]]
[[1.         0.99948862]
 [0.99948862 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99945118]
 [0.99945118 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99916515]
 [0.99916515 1.        ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99952855]
 [0.99952855 1

[[1. 1.]
 [1. 1.]]
[[1.         0.99951397]
 [0.99951397 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99961263]
 [0.99961263 1.        ]]
[[1.        0.9995138]
 [0.9995138 1.       ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99967733]
 [0.99967733 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99978474]
 [0.99978474 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951336]
 [0.99951336 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99981664]
 [0.99981664 1.    

[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.       0.994426]
 [0.994426 1.      ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99791066]
 [0.99791066 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1.         0.99790327]
 [0.99790327 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99974361]
 [0.99974361 1.        ]]
[[1.         0.99961539]
 [0.99961539 1.        ]]
[[1.         0.99833661]
 [0.99833661 1.        ]]
[[1.         0.99967733]
 [0.99967733 1.        ]]
[[1.         0.99910036]
 [0.99910036 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99978474]
 [0

[[1.        0.9995457]
 [0.9995457 1.       ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1.         0.99951134]
 [0.99951134 1.        ]]
[[1.         0.99028849]
 [0.99028849 1.        ]]
[[1.         0.99951381]
 [0.99951381 1.        ]]
[[1.         0.99999964]
 [0.99999964 1.        ]]
[[1.         0.99902017]
 [0.99902017 1.        ]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1.         0.99808606]
 [0.99808606 1.        ]]
[[1.         0.99999964]
 [0.99999964 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99981664]
 [0.99981664 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1.        0.9984429]
 [0.9984429 1.       ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99637436]
 [0.99637436 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [

[[1. 1.]
 [1. 1.]]
[[1.         0.99791349]
 [0.99791349 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99728224]
 [0.99728224 1.        ]]
[[1.         0.99965141]
 [0.99965141 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99796613]
 [0.99796613 1.        ]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1.         0.99950552]
 [0.99950552 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99684511]
 [0.99684511 1.        ]]
[[1.         0.99972451]
 [0.99972451 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99888949]
 [0.99888949 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.        0.9998311]
 [0.9998311 1.       ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951058]
 [0.99951058 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.   

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99695623]
 [0.99695623 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99974505]
 [0.99974505 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951336]
 [0.99951336 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99974853]
 [0.99974853 1.        ]]
[[1.         0.99795007]
 [0.99795007 1.        ]]
[[1.         0.99840578]
 [0.99840578 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.        0.9994164]
 [0.9994164 1.       ]]
[[1.         0.99951381]
 [0.99951381 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951397]
 [0.99951397 1.        ]]
[[1.         0.99977582]
 [0.99977582 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.       0.99976

[[1.         0.99922021]
 [0.99922021 1.        ]]
[[1.         0.99948862]
 [0.99948862 1.        ]]
[[1.         0.99952855]
 [0.99952855 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951134]
 [0.99951134 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.        0.9995457]
 [0.9995457 1.       ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99978474]
 [0.99978474 1.        ]]
[[1.         0.99917082]
 [0.99917082 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.98645497]
 [0.98645497 1.        ]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99999964]
 [0.99999964

[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99927759]
 [0.99927759 1.        ]]
[[1.         0.99961607]
 [0.99961607 1.        ]]
[[1.         0.99978184]
 [0.99978184 1.        ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.        0.9485174]
 [0.9485174 1.       ]]
[[1.         0.99904347]
 [0.99904347 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99975306]
 [0.99975306 1.        ]]
[[1.         0.99974853]
 [0.99974853 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99523044]
 [0.99523044 1.        ]]
[[1.         0.98830449]
 [0.98830449 1.        ]]
[[1.         0.99978474]
 [0.99978474 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1.         0.99857448]
 [0.99857448 1.        ]]
[[1. 1.]
 [1. 1.]

[[1.         0.99978418]
 [0.99978418 1.        ]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951381]
 [0.99951381 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.98997662]
 [0.98997662 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99976544]
 [0.99976544 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99951336]
 [0.99951336 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99880724]
 [0.99880724 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99886014]
 [0.99886014 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99999861]
 [0.99999861 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99952855]
 [0.99952855 1.        ]]
[[1.         0.99980936]
 [0.99980936 1.        ]]
[[1.         0.99913579]
 [0.99913579 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99977582]
 [0.99977582 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99981664]
 [0.99981664 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1.         0.99980165]
 [0.99980165 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99977418]
 [0.99977418 1.        ]]
[[1.         0.99459783]
 [0.99459783 1.        ]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1.         0.99999964]
 [0.99999964 1.        ]]
[[1.         0.99917082]
 [0.99917082 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1.         

[[1.         0.99139428]
 [0.99139428 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99975689]
 [0.99975689 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99577452]
 [0.99577452 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99724255]
 [0.99724255 1.        ]]
[[1.         0.99978311]
 [0.99978311 1.        ]]
[[1.         0.99953676]
 [0.99953676 1.        ]]
[[1.         0.99978311]
 [0.99978311 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1.         0.99896672]
 [0.99896672 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99945891]
 [0.99945891 1.        ]]
[[1.         0.99979345]
 [0.99979345 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1.         0.99776042]
 [0.99776042 1.        ]]
[[1.         0.99963698]
 [0.99963698 1.        ]]
[[1.         0.99448504]
 [0.99448504 1.        ]]
[[1.         0.99916213]
 [0.99916213 1.        ]]
[[1.         0.99974853]
 [0.99974853 1.        ]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


KeyboardInterrupt: 

In [4]:
counts_by_image[9] / counts_by_image[9].sum()

array([0.  , 0.66, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.34])

In [7]:
np.exp(np.log(counts_by_image[9])/10) / np.exp(np.log(counts_by_image[9])/10).sum()

/home/joshuacp/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([0.        , 0.51657628, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.48342372])

In [101]:
(counts_by_image[9] + 0.000001) / (counts_by_image[9] + 0.000001).sum()

array([1.99999960e-08, 6.59999888e-01, 1.99999960e-08, 1.99999960e-08,
       1.99999960e-08, 1.99999960e-08, 1.99999960e-08, 1.99999960e-08,
       1.99999960e-08, 3.39999952e-01])